### ISSUE TITLE
Clarify goal of repo in README.md

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/sensu-plugins-skel#1]
I love that this skeleton is out there for people to adopt. It would be helpful to refactor the main README.md to explain how someone might get started using it. 

For organization sake, we could move `README.md`->`README-skel.md` and make a separate on that helps people get started. I love how Slack has clear scoping in its sections, especially the ["Useful to Me?" part](https://github.com/slack-ruby/slack-ruby-client#useful-to-me). We could adopt similar file layout.

**Comment by majormoses** [comment]
Put together a PR and I will review it.
