### ISSUE TITLE
Add testing framework to skeleton repo

### ISSUE THREAD

**Issue by Evesy** [sensu-plugins/sensu-plugins-skel#9]
Would it be a good idea to include a (hopefully self documenting) testing framework within the skeleton repo for new plugins to take advantage of, and also any users wishing to add tests to existing plugins -- Copying the layout of the testing in the dcos plugin for example.

Obviously not all plugins are going to be able to use the same the exact same testing setup, however it'd at least serve as a single starting point to users, to save having to click through repos to find a plugin with good tests.

It could just include:

- Sample kitchen file with multiple Ruby suites
- Sample fixtures (i.e. Kitchen bootstrap script, or sample data for stub requests)
- Sample serverspec tests

Happy put this in place (using dcos as an example) if it's wanted.

**Comment by thomasriley** [comment]
I think this is a great idea, good to have some standards & documentation in place that encourage test driven development.

**Comment by majormoses** [comment]
I think I got the majority of the actual skel work in #10 the best practices should be addressed here: https://github.com/sensu-plugins/community/issues/46 and I will get on that after some blog posts come out on this subject that I will use to help people understand more.

**Comment by majormoses** [comment]
For example tests that are commented out I used DNS as that is a fairly universal tech and does not really require any mocking of data beyond creating the DNS records for testing.

**Comment by majormoses** [comment]
They are live now:
- https://blog.sensuapp.org/our-approach-to-testing-sensu-plugins-869260eba94c
- https://blog.sensuapp.org/writing-sensu-plugin-tests-with-test-kitchen-and-serverspec-b646d2eeee51

**Comment by majormoses** [comment]
do we need anything more that #10 has landed? Regarding docs, let's keep that on the community issue ref'd.

**Comment by majormoses** [comment]
I'm closing this out as there is now something there and no one has clarified if there is anything else that should be added.
